package:
  name: chainguard-keys
  version: 0
  epoch: 5
  description: "Chainguard public keys"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"/etc/apk/keys
      install -m644 chainguard-extras.rsa.pub "${{targets.destdir}}"/etc/apk/keys
      install -m644 chainguard-enterprise.rsa.pub "${{targets.destdir}}"/etc/apk/keys

      for i in x86_64 aarch64; do
        mkdir -p "${{targets.destdir}}"/usr/share/apk/keys/${i}
        install -m644 chainguard-extras.rsa.pub "${{targets.destdir}}"/usr/share/apk/keys/${i}/chainguard-extras.rsa.pub
        install -m644 chainguard-enterprise.rsa.pub "${{targets.destdir}}"/usr/share/apk/keys/${i}/chainguard-enterprise.rsa.pub
      done

update:
  enabled: false
